---
kind: pipeline
name: Release

trigger:
  ref:
  - refs/tags/v*
  event:
  - tag

clone:
  skip_verify: true

steps:

- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version
  - yarn --version
  - git --version 

- name: install
  image: node:lts
  commands:
    - npm install

- name: npm_release
  image: plugins/npm
  settings:
    username:
      from_secret: NPM_USERNAME
    password:
      from_secret: NPM_PASSWORD
    email:
      from_secret: NPM_EMAIL

